context:
  # Version sourced from upstream package.xml
  name: abb-libegm
  version: 1.2.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  git: https://github.com/ros-industrial/abb_libegm
  rev: 2c9350abfb67131cae796805fed8cd6eeb2ab7f9

build:
  number: 2

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
    - libprotobuf
  host:
    - libprotobuf
    - libboost-devel >=1.84,<1.87

tests:
  - package_contents:
      lib:
        - abb_libegm
      include:
        - abb_libegm/egm_base_interface.h
        - abb_libegm/egm_controller_interface.h

about:
  homepage: https://github.com/ros-industrial/abb_libegm
  license: BSD-3-Clause
  license_file: LICENSE
  summary: ABB ROS2 EGM client library
  description: |
    A C++ library for interacting with ABB robots using the
    External Guided Motion (EGM) interface.
  repository: https://github.com/ros-industrial/abb_libegm

extra:
  recipe-maintainers:
    - Carlo-Rosso
